const products = [
  {id:1, name:'AURELIS Chronograph', collection:'sport', price:12800, ref:'AU-CHR-01', image:'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Aniq ritm va kuchli kontrastlar bilan yaratilgan zamonaviy xronograf.',ru:'Современный хронограф с чётким ритмом и выразительными контрастами.',en:'A contemporary chronograph built around precise rhythm and restrained contrast.'}, specs:{movement:'AURELIS Cal. 41',material:'316L Steel',diameter:'42 mm',thickness:'13.2 mm',water:'100 m',power:'60 h',strap:'Black calfskin',crystal:'Sapphire',comp:'Chronograph',edition:'Limited · 250 pieces'}},
  {id:2, name:'AURELIS Classic', collection:'classic', price:9400, ref:'AU-CLS-02', image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Sokin siluet, nozik ko‘rsatkichlar va abadiy klassik nisbatlar.',ru:'Спокойный силуэт, тонкие индексы и вне времени выверенные пропорции.',en:'A quiet silhouette, slender indices and proportions designed to outlast trends.'}, specs:{movement:'AURELIS Cal. 31',material:'18K Rose Gold',diameter:'39 mm',thickness:'9.8 mm',water:'50 m',power:'72 h',strap:'Alligator leather',crystal:'Sapphire',comp:'Small seconds',edition:'Permanent collection'}},
  {id:3, name:'AURELIS Royal', collection:'classic', price:17200, ref:'AU-RYL-03', image:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Arxitektura ilhomidagi korpus, sayqallangan yuzalar va zargarlik detali.',ru:'Архитектурный корпус, полированные поверхности и ювелирные акценты.',en:'An architectural case with polished surfaces and jewellery-grade finishing.'}, specs:{movement:'AURELIS Cal. 52',material:'18K White Gold',diameter:'41 mm',thickness:'10.2 mm',water:'50 m',power:'65 h',strap:'Black alligator',crystal:'Sapphire',comp:'Date',edition:'Permanent collection'}},
  {id:4, name:'AURELIS Eclipse', collection:'atelier', price:14900, ref:'AU-ECL-04', image:'https://images.unsplash.com/photo-1495857000853-fe46c8aefc30?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Qorong‘i siferblat va issiq oltin aksentlar bilan tungi xarakter.',ru:'Ночной характер: тёмный циферблат и тёплые золотые акценты.',en:'A nocturnal character defined by a dark dial and warm metallic accents.'}, specs:{movement:'AURELIS Cal. 44',material:'Black PVD Steel',diameter:'40 mm',thickness:'11.1 mm',water:'100 m',power:'72 h',strap:'Textured leather',crystal:'Sapphire',comp:'Moon phase',edition:'Limited · 150 pieces'}},
  {id:5, name:'AURELIS Marine', collection:'sport', price:11600, ref:'AU-MRN-05', image:'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Suvga chidamli, yengil va harakat uchun qurilgan sport modeli.',ru:'Водостойкая, лёгкая модель для движения и повседневного ритма.',en:'Water-ready, balanced and built for movement without losing refinement.'}, specs:{movement:'AURELIS Cal. 36',material:'316L Steel',diameter:'41.5 mm',thickness:'12.1 mm',water:'200 m',power:'60 h',strap:'Steel bracelet',crystal:'Sapphire',comp:'Date',edition:'Permanent collection'}},
  {id:6, name:'AURELIS Tourbillon', collection:'atelier', price:32900, ref:'AU-TRB-06', image:'https://images.unsplash.com/photo-1577743628234-2c2f7c5c5f2b?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Ko‘zga tashlanadigan tourbillon va qo‘l bilan bezatilgan mexanizm.',ru:'Выразительный турбийон и вручную декорированный механизм.',en:'A statement tourbillon with a hand-decorated movement at its centre.'}, specs:{movement:'AURELIS Cal. T90',material:'Platinum 950',diameter:'42 mm',thickness:'12.9 mm',water:'30 m',power:'72 h',strap:'Alligator leather',crystal:'Sapphire',comp:'Flying tourbillon',edition:'Limited · 88 pieces'}},
  {id:7, name:'AURELIS Heritage', collection:'classic', price:10900, ref:'AU-HER-07', image:'https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Tarixiy ruh va zamonaviy ergonomika o‘rtasidagi muvozanat.',ru:'Баланс между историческим характером и современной эргономикой.',en:'A measured dialogue between heritage cues and modern ergonomics.'}, specs:{movement:'AURELIS Cal. 28',material:'18K Yellow Gold',diameter:'38.5 mm',thickness:'9.4 mm',water:'50 m',power:'55 h',strap:'Brown calfskin',crystal:'Sapphire',comp:'Date',edition:'Permanent collection'}},
  {id:8, name:'AURELIS Grand Date', collection:'atelier', price:18900, ref:'AU-GDT-08', image:'https://images.unsplash.com/photo-1518544889284-7f4d9e2f5c9e?auto=format&fit=crop&w=1400&q=88', desc:{uz:'Katta sana displeyi, muvozanatli korpus va sakinatli arxitektura.',ru:'Крупная дата, сбалансированный корпус и спокойная архитектура циферблата.',en:'A generous date aperture, balanced proportions and a calm architectural dial.'}, specs:{movement:'AURELIS Cal. 56',material:'18K Rose Gold',diameter:'41 mm',thickness:'10.5 mm',water:'50 m',power:'72 h',strap:'Black alligator',crystal:'Sapphire',comp:'Grand date',edition:'Limited · 200 pieces'}}
];

const boutiques = [
  ['Dubai','United Arab Emirates',25.2048,55.2708],['Paris','France',48.8566,2.3522],['London','United Kingdom',51.5074,-0.1278],['Geneva','Switzerland',46.2044,6.1432],['New York','United States',40.7128,-74.006],['Tokyo','Japan',35.6762,139.6503],['Singapore','Singapore',1.3521,103.8198],['Tashkent','Uzbekistan',41.2995,69.2401]
];

const i18n = {
  uz:{nav:{collections:'Collections',watches:'Soatlar',heritage:'Meros',craftsmanship:'Usta mehnati',journal:'Jurnal',boutiques:'Butiklar'},header:{bag:'Sumka'},hero:{eyebrow:'AURELIS MANUFACTURE · 01',title:'VAQT, MUKAMMALLIKKA AYLANADI.',sub:'Avlodlar uchun yaratilgan noyob soatlar.',cta1:'TO‘PLAMNI KO‘RISH',cta2:'BRENDNI KASHF ETISH'},manifesto:'AURELIS — an’ana, aniqlik va zamonaviy dizayn uyg‘unligi.',collections:{title:'AURELIS TO‘PLAMI'},filters:{all:'Barchasi',classic:'Classic',sport:'Sport',atelier:'Atelier'},feature:{eyebrow:'AURELIS GRAND DATE',title:'Aniqlik, salobat bilan.',text:'Muvozanatli korpus, qo‘l bilan ishlangan yuzalar va sokin arxitekturali siferblat — kundalik marosimlar uchun umrboqiy yaratilgan.'},common:{explore:'Soatni ko‘rish',viewJournal:'Jurnalni ko‘rish',read:'Maqolani o‘qish'},craft:{title:'QO‘L MEHNATI. MUKAMMALLIKKA YETKAZILGAN.',text:'Har bir detal yakuniy jiloga yetguniga qadar qo‘l bilan nazorat qilinadi.',metric1:'komponent',metric2:'qo‘l bilan ishlov bosqichi',metric3:'quvvat zaxirasi'},heritage:{title:'Vaqtni o‘lchashdan ko‘ra, uni his qilish.',text:'AURELIS an’ana, aniqlik va zamonaviy dizayn uyg‘unligi sifatida qurilgan. Har bir kolleksiya sokin kuch va uzoq umr uchun yaratiladi.'},wrist:{title:'Bilakda. Har bir lahzada.',note:'Formal. Business. Evening. Travel.'},journal:{title:'Mexanik vaqt. Tirik meros.',a1:'Mexanik soat san’ati',a2:'AURELIS manufakturasining ichida',a3:'Hashamatli soat qanday yaratiladi?'},boutiques:{title:'AURELIS BUTIKLARI',cta:'BUTIKNI TOPISH'},search:{title:'Soatlar va maqolalarni qidiring'},bag:{title:'Xarid sumkasi',total:'Jami',checkout:'TO‘LOVGA O‘TISH'},account:{title:'AURELIS akkaunti'},footer:{tag:'AURELIS dunyosini kashf eting.',newsletter:'AURELIS dunyosini kashf eting.',explore:'Kashf eting',services:'Xizmatlar',contact:'Aloqa',care:'Parvarish qo‘llanmasi',shipping:'Yetkazib berish',legal:'Huquqiy'},messages:{added:'Sumkaga qo‘shildi',newsletter:'Rahmat. Yangiliklar sizga yuboriladi.',account:'Namuna akkauntiga kirildi.',empty:'Sumka hozircha bo‘sh.',searchEmpty:'Mos natija topilmadi.',checkout:'Checkout hozircha demo rejimida.'}},
  ru:{nav:{collections:'Коллекции',watches:'Часы',heritage:'Наследие',craftsmanship:'Мастерство',journal:'Журнал',boutiques:'Бутики'},header:{bag:'Сумка'},hero:{eyebrow:'МАНУФАКТУРА AURELIS · 01',title:'ВРЕМЯ, ВОПЛОЩЁННОЕ В СОВЕРШЕНСТВЕ.',sub:'Исключительные часы, созданные на поколения.',cta1:'СМОТРЕТЬ КОЛЛЕКЦИЮ',cta2:'ОТКРЫТЬ БРЕНД'},manifesto:'AURELIS — сочетание традиций, точности и современного дизайна.',collections:{title:'КОЛЛЕКЦИЯ AURELIS'},filters:{all:'Все',classic:'Classic',sport:'Sport',atelier:'Atelier'},feature:{eyebrow:'AURELIS GRAND DATE',title:'Точность, обретающая характер.',text:'Сбалансированный корпус, ручная обработка поверхностей и спокойная архитектура циферблата — для ритуалов, которые остаются с вами надолго.'},common:{explore:'Смотреть часы',viewJournal:'Открыть журнал',read:'Читать историю'},craft:{title:'РУЧНАЯ РАБОТА. СОВЕРШЕНСТВО В КАЖДОЙ ДЕТАЛИ.',text:'Каждый элемент проходит ручной контроль до достижения финальной отделки.',metric1:'компонента',metric2:'этапа ручной отделки',metric3:'запас хода'},heritage:{title:'Не просто измерять время — проживать его.',text:'AURELIS соединяет традиционное часовое дело, точность и современный дизайн. Каждая коллекция создана для тихой силы и долгой жизни.'},wrist:{title:'На запястье. В каждом моменте.',note:'Formal. Business. Evening. Travel.'},journal:{title:'Механическое время. Живое наследие.',a1:'Искусство механических часов',a2:'Внутри мануфактуры AURELIS',a3:'Как создаются роскошные часы?'},boutiques:{title:'БУТИКИ AURELIS',cta:'НАЙТИ БУТИК'},search:{title:'Поиск часов и историй'},bag:{title:'Корзина',total:'Итого',checkout:'К ОПЛАТЕ'},account:{title:'Аккаунт AURELIS'},footer:{tag:'Откройте для себя мир AURELIS.',newsletter:'Откройте для себя мир AURELIS.',explore:'О бренде',services:'Сервис',contact:'Контакты',care:'Уход за часами',shipping:'Доставка',legal:'Правовая информация'},messages:{added:'Добавлено в корзину',newsletter:'Спасибо. Новости будут отправлены вам.',account:'Вход выполнен в демо-аккаунт.',empty:'Корзина пуста.',searchEmpty:'Совпадений не найдено.',checkout:'Оформление заказа пока работает в демо-режиме.'}},
  en:{nav:{collections:'Collections',watches:'Watches',heritage:'Heritage',craftsmanship:'Craftsmanship',journal:'Journal',boutiques:'Boutiques'},header:{bag:'Bag'},hero:{eyebrow:'AURELIS MANUFACTURE · 01',title:'TIME, REFINED.',sub:'Exceptional watches, crafted for generations.',cta1:'EXPLORE THE COLLECTION',cta2:'DISCOVER THE BRAND'},manifesto:'AURELIS combines traditional watchmaking, precision, and contemporary design.',collections:{title:'THE AURELIS COLLECTION'},filters:{all:'All',classic:'Classic',sport:'Sport',atelier:'Atelier'},feature:{eyebrow:'AURELIS GRAND DATE',title:'Precision, given presence.',text:'A balanced case, hand-finished surfaces and a calm architectural dial — engineered for a lifetime of daily rituals.'},common:{explore:'Explore the watch',viewJournal:'View journal',read:'Read story'},craft:{title:'CRAFTED BY HAND. PERFECTED OVER TIME.',text:'Every detail is inspected by hand until the final finish meets our standard.',metric1:'components',metric2:'hand-finishing steps',metric3:'power reserve'},heritage:{title:'More than measuring time — inhabiting it.',text:'AURELIS combines traditional watchmaking, precision and contemporary design. Each collection is shaped for quiet strength and long life.'},wrist:{title:'On the wrist. In every moment.',note:'Formal. Business. Evening. Travel.'},journal:{title:'Mechanical time. A living heritage.',a1:'The Art of Mechanical Watchmaking',a2:'Inside the AURELIS Manufacture',a3:'How a Luxury Watch Is Made'},boutiques:{title:'AURELIS BOUTIQUES',cta:'FIND A BOUTIQUE'},search:{title:'Search watches & stories'},bag:{title:'Shopping Bag',total:'Total',checkout:'CHECKOUT'},account:{title:'AURELIS Account'},footer:{tag:'Discover the world of AURELIS.',newsletter:'Discover the world of AURELIS.',explore:'Explore',services:'Services',contact:'Contact',care:'Care Guide',shipping:'Shipping',legal:'Legal'},messages:{added:'Added to bag',newsletter:'Thank you. News will be sent to you.',account:'Signed in to demo account.',empty:'Your bag is empty.',searchEmpty:'No matches found.',checkout:'Checkout is currently in demo mode.'}}
};

let lang='uz';
let bag=[];
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const money=n=>`$${n.toLocaleString('en-US')}`;
const t=(path)=>path.split('.').reduce((o,k)=>o?.[k],i18n[lang])||path;

function applyLang(){document.documentElement.lang=lang;$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderProducts();renderBoutiques();renderBag();renderSearch();}
function renderProducts(filter='all'){
  const grid=$('#productGrid');
  grid.innerHTML=products.map((p,i)=>{
    const visible=filter==='all'||p.collection===filter;
    return `<article class="product-card reveal ${visible?'':'hidden'}" data-id="${p.id}"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}"></div><div class="product-meta"><div class="product-top"><span>${p.collection}</span><span>${p.ref}</span></div><h3 class="product-name">${p.name}</h3><p class="product-desc">${p.desc[lang]}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><span class="product-open">${t('common.explore')}</span></div></div></article>`
  }).join('');
  $$('.product-card').forEach(card=>card.addEventListener('click',()=>openProduct(+card.dataset.id)));
}
function openProduct(id){
  const p=products.find(x=>x.id===id); if(!p)return;
  $('#productDetail').innerHTML=`<div class="product-detail"><div class="detail-gallery"><img src="${p.image}" alt="${p.name}"></div><div class="detail-copy"><span class="eyebrow light">${p.collection.toUpperCase()} · ${p.ref}</span><h2 class="product-name">${p.name}</h2><p class="product-desc">${p.desc[lang]}</p><div class="detail-price">${money(p.price)}</div><div class="spec-grid">${Object.entries({Movement:p.specs.movement,Material:p.specs.material,Diameter:p.specs.diameter,Thickness:p.specs.thickness,'Water resistance':p.specs.water,'Power reserve':p.specs.power,Bracelet:p.specs.strap,Crystal:p.specs.crystal,Complications:p.specs.comp,Edition:p.specs.edition}).map(([k,v])=>`<div class="spec"><small>${k}</small><span>${v}</span></div>`).join('')}</div><div class="detail-actions"><button class="btn btn-light" id="detailAdd">ADD TO BAG</button><button class="btn btn-ghost" id="detailAdvisor">CONTACT AN ADVISOR</button></div></div></div>`;
  $('#productModal').classList.add('open');
  $('#detailAdd').onclick=()=>{addToBag(id);toast(t('messages.added'));};
  $('#detailAdvisor').onclick=()=>toast(lang==='uz'?'Maslahatchi bilan bog‘lanish demo rejimida.':lang==='ru'?'Связь с консультантом в демо-режиме.':'Advisor contact is in demo mode.');
}
function closeEl(id){$('#'+id)?.classList.remove('open'); if(id==='bagDrawer'||id==='accountDrawer')$('#'+id).style.right='';}
function addToBag(id){bag.push(id);renderBag();$('#bagDrawer').classList.add('open');}
function renderBag(){const items=$('#bagItems');$('#bagCount').textContent=bag.length; if(!bag.length){items.innerHTML=`<div style="padding:40px 0;color:#77736d">${t('messages.empty')}</div>`;$('#bagTotal').textContent='$0';return} const counts={};bag.forEach(id=>counts[id]=(counts[id]||0)+1); items.innerHTML=Object.entries(counts).map(([id,q])=>{const p=products.find(x=>x.id==id);return `<div class="bag-row"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><p>${q} × ${money(p.price)}</p><p>${p.ref}</p></div><button data-remove="${p.id}">×</button></div>`}).join(''); items.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const idx=bag.indexOf(+b.dataset.remove);if(idx>-1)bag.splice(idx,1);renderBag()}); $('#bagTotal').textContent=money(bag.reduce((s,id)=>s+products.find(p=>p.id===id).price,0));}
function renderSearch(query=''){const r=$('#searchResults'); if(!query){r.innerHTML='<div style="padding-top:24px;color:#77736d;font-size:12px;letter-spacing:.08em">Type a model, collection or reference.</div>';return} const q=query.toLowerCase(); const hits=products.filter(p=>`${p.name} ${p.collection} ${p.ref} ${Object.values(p.desc).join(' ')}`.toLowerCase().includes(q));r.innerHTML=hits.length?hits.map(p=>`<div class="search-result" data-search-id="${p.id}"><div>${p.name}</div><small>${p.ref}</small></div>`).join(''):`<div style="padding-top:24px;color:#77736d">${t('messages.searchEmpty')}</div>`;r.querySelectorAll('[data-search-id]').forEach(x=>x.onclick=()=>{closeEl('searchOverlay');openProduct(+x.dataset.searchId)});}
function renderBoutiques(){const list=$('#boutiqueList');list.innerHTML=boutiques.map((b,i)=>`<div class="boutique-row"><div><strong>${b[0]}</strong><span>${b[1]}</span></div><button data-pin="${i}" aria-label="${b[0]}">↗</button></div>`).join(''); if(window.boutiqueMap){window.boutiqueMap.eachLayer(l=>{if(l._aurelisPin)window.boutiqueMap.removeLayer(l)}); boutiqueMarkers();}}
function initMap(){if(!window.L||!document.getElementById('boutiqueMap'))return;window.boutiqueMap=L.map('boutiqueMap',{zoomControl:false,scrollWheelZoom:false}).setView([36,36],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(boutiqueMap);L.control.zoom({position:'bottomright'}).addTo(boutiqueMap);boutiqueMarkers();}
function boutiqueMarkers(){boutiques.forEach((b,i)=>{const icon=L.divIcon({className:'',html:'<div class="pin-icon"></div>',iconSize:[12,12],iconAnchor:[6,6]});const m=L.marker([b[2],b[3]],{icon}).addTo(boutiqueMap).bindPopup(`<strong>${b[0]}</strong><br>${b[1]}`);m._aurelisPin=true;});}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}

window.addEventListener('scroll',()=>{$('#siteHeader').classList.toggle('scrolled',scrollY>30);document.querySelector('.feature-wrap')?.classList.toggle('in-view',scrollY>document.querySelector('.feature-wrap').offsetTop-600)});
document.addEventListener('mousemove',e=>{const g=$('.cursor-glow');if(g){g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'}});
$$('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;applyLang()}));
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeEl(b.dataset.close)));
$('#searchBtn').onclick=()=>{$('#searchOverlay').classList.add('open');$('#searchInput').focus()}; $('#bagBtn').onclick=()=>{$('#bagDrawer').classList.add('open')}; $('#accountBtn').onclick=()=>{$('#accountDrawer').classList.add('open')};
$('#searchInput').addEventListener('input',e=>renderSearch(e.target.value));
$('#checkoutBtn').onclick=()=>toast(t('messages.checkout'));
$('#findBoutique').onclick=()=>document.querySelector('#boutiques').scrollIntoView({behavior:'smooth'});
$('#filterControls').addEventListener('click',e=>{if(!e.target.classList.contains('filter'))return;$$('.filter').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderProducts(e.target.dataset.filter)});
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.target.reset();$('#newsletterMsg').textContent=t('messages.newsletter');});
$('#accountForm').addEventListener('submit',e=>{e.preventDefault();$('#accountMsg').textContent=t('messages.account')});
$$('[data-account-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-account-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));

document.addEventListener('keydown',e=>{if(e.key==='Escape'){['searchOverlay','productModal'].forEach(closeEl);$('#bagDrawer').classList.remove('open');$('#accountDrawer').classList.remove('open')}});

applyLang();
initMap();

if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(ent=>{if(ent.isIntersecting)ent.target.classList.add('in-view')}),{threshold:.12});document.querySelectorAll('.reveal,.craft,.heritage-copy,.journal-card').forEach(el=>{el.classList.add('reveal');io.observe(el)});}
